OWNER_NAME="𝙈𝘼𝙇𝙄𝘽𝙐 𝙏𝙃𝙀𝙀 𝙂𝙍𝙀𝘼𝙏"
PREFIX="."
PUBLIC_MODE='yes'
AUTO_READ_STATUS="yes"
AUTO_DOWNLOAD_STATUS="no"
BOT_NAME= "𝙈𝘼𝙇𝙄𝘽𝙐-𝙈𝘿"
IMAGE_MENU= "https://telegra.ph/file/0f550c4bf2bdcb9b2e9ce.jpg"
NUMERO_OWNER= ""
OWNER_NAME= "᚛Malibu᚜"
DATABASE_URL= ""
WARN_COUNT= ""
OPENAI_API_KEY= ""
STARTING_BOT_MESSAGE='yes'
ANTI_DELETE_MESSAGE='yes'
